Update paymentservice.yaml

diff --git a/kubernetes-files/paymentservice.yaml b/kubernetes-files/paymentservice.yaml
--- a/kubernetes-files/paymentservice.yaml
+++ b/kubernetes-files/paymentservice.yaml
@@ -1,28 +1,40 @@
-
+---
 apiVersion: apps/v1
 kind: Deployment
 metadata:
-  name: paymentservice
-  labels:
-    app: paymentservice
+  name: loadgenerator
 spec:
   selector:
     matchLabels:
-      app: paymentservice
+      app: loadgenerator
+  replicas: 1
   template:
     metadata:
       labels:
-        app: paymentservice
+        app: loadgenerator
+      annotations:
+        sidecar.istio.io/rewriteAppHTTPProbers: "true"
     spec:
-      serviceAccountName: paymentservice
+      serviceAccountName: default
       terminationGracePeriodSeconds: 5
+      restartPolicy: Always
       securityContext:
         fsGroup: 1000
         runAsGroup: 1000
         runAsNonRoot: true
         runAsUser: 1000
-      containers:
-      - name: server
+      initContainers:
+      - command:
+        - /bin/sh
+        - -exc
+        - |
+          echo "Init container pinging frontend: ${FRONTEND_ADDR}..."
+          STATUSCODE=$(wget --server-response http://${FRONTEND_ADDR} 2>&1 | awk '/^  HTTP/{print $2}')
+          if test $STATUSCODE -ne 200; then
+              echo "Error: Could not reach frontend - Status code: ${STATUSCODE}"
+              exit 1
+          fi
+        name: frontend-check
         securityContext:
           allowPrivilegeEscalation: false
           capabilities:
@@ -30,44 +42,29 @@ spec:
               - ALL
           privileged: false
           readOnlyRootFilesystem: true
-        image: 421954350274.dkr.ecr.us-east-1.amazonaws.com/paymentservice:2
-        ports:
-        - containerPort: 50051
+        image: busybox:latest
         env:
-        - name: PORT
-          value: "50051"
-        - name: DISABLE_PROFILER
-          value: "1"
-        readinessProbe:
-          grpc:
-            port: 50051
-        livenessProbe:
-          grpc:
-            port: 50051
+        - name: FRONTEND_ADDR
+          value: "frontend:80"
+      containers:
+      - name: main
+        securityContext:
+          allowPrivilegeEscalation: false
+          capabilities:
+            drop:
+              - ALL
+          privileged: false
+          readOnlyRootFilesystem: true
+        image: 590183907926.dkr.ecr.us-east-1.amazonaws.com/loadgenerator:1   #please change the image url according to your account
+        env:
+        - name: FRONTEND_ADDR
+          value: "frontend:80"
+        - name: USERS
+          value: "10"
         resources:
           requests:
-            cpu: 100m
-            memory: 64Mi
+            cpu: 300m
+            memory: 256Mi
           limits:
-            cpu: 200m
-            memory: 128Mi
----
-apiVersion: v1
-kind: Service
-metadata:
-  name: paymentservice
-  labels:
-    app: paymentservice
-spec:
-  type: ClusterIP
-  selector:
-    app: paymentservice
-  ports:
-  - name: grpc
-    port: 50051
-    targetPort: 50051
----
-apiVersion: v1
-kind: ServiceAccount
-metadata:
-  name: paymentservice
+            cpu: 500m
+            memory: 512Mi
